### ISSUE TITLE
`import Database` failed

### ISSUE THREAD

**Issue by ChristianKniep** [josefbacik/kernelscope#3]
Currently creating a Dockerfile for it and I am wondering why the execution fails on me.
https://github.com/qnib/kernelscope/blob/dockerfile/Dockerfile
```
bash-4.3# python /opt/kernelscope/src/KernelscopeLoggerService.py --sqlite /var/lib/kernelscope.db 8081
Traceback (most recent call last):
  File "/opt/kernelscope/src/KernelscopeLoggerService.py", line 2, in <module>
    import KernelscopeCategories
  File "/opt/kernelscope/src/KernelscopeCategories.py", line 2, in <module>
    import Constraints
  File "/opt/kernelscope/src/Constraints.py", line 1, in <module>
    import Database
ImportError: No module named Database
bash-4.3#
```

Is a file `Database.py` missing?

**Comment by josefbacik** [comment]
Fixed it, but of course I put the wrong issue number in the commit.  Sorry about that.
